{% set opencl_devel_ver="1.2.0-2018050600" %}
{% set opencl_devel_sha256="8691bd36c47d76919de635b896322239875ec5afa49c5912232615ce6627063e" %}

package:
    name: roctools
    version: "0.0"

source:
  - path: ../..
  - fn: rocm-opencl-devel-{{ opencl_devel_ver }}.x86_64.rpm
    url: http://repo.radeon.com/rocm/yum/rpm/rocm-opencl-devel-{{ opencl_devel_ver }}.x86_64.rpm
    folder: opencl_tmp
    sha256: {{ opencl_devel_sha256 }}

build:
    number: 0

requirements:
  build:
    - {{ compiler('c') }} # [unix]
    - {{ compiler('cxx') }} # [unix]
    - cmake>=2.8
    - xz
    - zlib
    - bzip2
    - libarchive
    - llvmdev_amdgcn
    # gtest is used in the test binaries
    - gtest

  host:
    - zlib # for llvm binary tooling that is copied in

test:
  commands:
    # The librocmlite.so DSO is tested at compile time

    # Check llvm binaries actually run
    - opt --help
    - llc --help
    - llvm-link --help
    - ld.lld --help

about:
    home: https://github.com/numba/roctools
    license: BSD
    summary: A shared library that wraps LLVM for code
             generation for devices with Radeon Open Compute support.
#     license_file: LICENSE.TXT
